name: fluttrr
description: "Connect for platonic local events and friendships in Kansas City and beyond."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.1.0
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.1.3+2
  gradient_borders: ^1.0.1
  flutter_card_swiper: ^7.2.0
  carousel_slider: ^5.0.0
  simple_gradient_text: ^1.3.0
  material_tag_editor: ^0.1.2
  get: ^4.6.6
  http: ^1.2.2
  google_sign_in: ^6.2.2
  top_snackbar_flutter: ^3.1.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2   # For encrypted token storage
  shimmer: ^3.0.0
  location: ^6.0.2
  geolocator: ^12.0.0
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  timeago: ^3.7.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.3
  socket_io_client: ^2.0.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.4.4
  flutter_stripe: ^11.4.0
  mapbox_maps_flutter: ^2.18.0
  gradient_progress_indicator: ^1.0.0+5  # For loading indicators
  image_picker: ^1.1.2                   # For photo uploads
  geocode: ^1.0.3                        # For address lookup
  flutter_map: ^8.1.0                    # Map widget
  latlong2: ^0.9.1                       # Needed for flutter_map
  url_launcher: ^6.2.5                   # For opening URLs
  geocoding: ^3.0.0                      # For geocoding (address to coordinates)
  sensors_plus: ^6.0.1                   # For shake detection (feedback)
  connectivity_plus: ^6.0.5              # For network connectivity status

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/

