// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        // Fuchsia uses web config as fallback
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwogGYT41STGgZdaentXG854Fxv2t9K0',
    appId: '1:174536441327:web:8b7aba45a991c3285c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    authDomain: 'tripmate-675c8.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwogGYT41STGgZdaentXG854Fxv2t9K0',
    appId: '1:174536441327:android:8b7aba45a991c3285c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8s9TLIShjHjzX17OwneGqGPsqZzMA9G8',
    appId: '1:174536441327:ios:91e93d742589d3735c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    iosClientId: '174536441327-rqdkhisgf5kegfmpksr2b4mnk1p2d9qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8s9TLIShjHjzX17OwneGqGPsqZzMA9G8',
    appId: '1:174536441327:ios:91e93d742589d3735c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    iosClientId: '174536441327-rqdkhisgf5kegfmpksr2b4mnk1p2d9qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlwogGYT41STGgZdaentXG854Fxv2t9K0',
    appId: '1:174536441327:web:8b7aba45a991c3285c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    authDomain: 'tripmate-675c8.firebaseapp.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBlwogGYT41STGgZdaentXG854Fxv2t9K0',
    appId: '1:174536441327:web:8b7aba45a991c3285c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    authDomain: 'tripmate-675c8.firebaseapp.com',
  );
}
